-- AlterEnum
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'MANAGEMENT';

-- AlterEnum
ALTER TYPE "PlanStatus" ADD VALUE IF NOT EXISTS 'AWAITING_MANAGEMENT_APPROVAL';
ALTER TYPE "PlanStatus" ADD VALUE IF NOT EXISTS 'MANAGEMENT_APPROVED';
ALTER TYPE "PlanStatus" ADD VALUE IF NOT EXISTS 'MANAGEMENT_REJECTED';
